// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"drive/ent/directory"
	"drive/ent/email"
	"drive/ent/object"
	"drive/ent/social"
	"drive/ent/user"
	"drive/ent/wechat"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"strconv"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/vmihailenco/msgpack/v5"
)

// OrderDirection defines the directions in which to order a list of items.
type OrderDirection string

const (
	// OrderDirectionAsc specifies an ascending order.
	OrderDirectionAsc OrderDirection = "ASC"
	// OrderDirectionDesc specifies a descending order.
	OrderDirectionDesc OrderDirection = "DESC"
)

// Validate the order direction value.
func (o OrderDirection) Validate() error {
	if o != OrderDirectionAsc && o != OrderDirectionDesc {
		return fmt.Errorf("%s is not a valid OrderDirection", o)
	}
	return nil
}

// String implements fmt.Stringer interface.
func (o OrderDirection) String() string {
	return string(o)
}

// MarshalGQL implements graphql.Marshaler interface.
func (o OrderDirection) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(o.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (o *OrderDirection) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("order direction %T must be a string", val)
	}
	*o = OrderDirection(str)
	return o.Validate()
}

func (o OrderDirection) reverse() OrderDirection {
	if o == OrderDirectionDesc {
		return OrderDirectionAsc
	}
	return OrderDirectionDesc
}

func (o OrderDirection) orderFunc(field string) OrderFunc {
	if o == OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

func cursorsToPredicates(direction OrderDirection, after, before *Cursor, field, idField string) []func(s *sql.Selector) {
	var predicates []func(s *sql.Selector)
	if after != nil {
		if after.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeGT
			} else {
				predicate = sql.CompositeLT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					after.Value, after.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.GT
			} else {
				predicate = sql.LT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					after.ID,
				))
			})
		}
	}
	if before != nil {
		if before.Value != nil {
			var predicate func([]string, ...interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.CompositeLT
			} else {
				predicate = sql.CompositeGT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.Columns(field, idField),
					before.Value, before.ID,
				))
			})
		} else {
			var predicate func(string, interface{}) *sql.Predicate
			if direction == OrderDirectionAsc {
				predicate = sql.LT
			} else {
				predicate = sql.GT
			}
			predicates = append(predicates, func(s *sql.Selector) {
				s.Where(predicate(
					s.C(idField),
					before.ID,
				))
			})
		}
	}
	return predicates
}

// PageInfo of a connection type.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *Cursor `json:"startCursor"`
	EndCursor       *Cursor `json:"endCursor"`
}

// Cursor of an edge type.
type Cursor struct {
	ID    int64 `msgpack:"i"`
	Value Value `msgpack:"v,omitempty"`
}

// MarshalGQL implements graphql.Marshaler interface.
func (c Cursor) MarshalGQL(w io.Writer) {
	quote := []byte{'"'}
	w.Write(quote)
	defer w.Write(quote)
	wc := base64.NewEncoder(base64.RawStdEncoding, w)
	defer wc.Close()
	_ = msgpack.NewEncoder(wc).Encode(c)
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (c *Cursor) UnmarshalGQL(v interface{}) error {
	s, ok := v.(string)
	if !ok {
		return fmt.Errorf("%T is not a string", v)
	}
	if err := msgpack.NewDecoder(
		base64.NewDecoder(
			base64.RawStdEncoding,
			strings.NewReader(s),
		),
	).Decode(c); err != nil {
		return fmt.Errorf("cannot decode cursor: %w", err)
	}
	return nil
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// DirectoryEdge is the edge representation of Directory.
type DirectoryEdge struct {
	Node   *Directory `json:"node"`
	Cursor Cursor     `json:"cursor"`
}

// DirectoryConnection is the connection containing edges to Directory.
type DirectoryConnection struct {
	Edges      []*DirectoryEdge `json:"edges"`
	PageInfo   PageInfo         `json:"pageInfo"`
	TotalCount int              `json:"totalCount"`
}

func (c *DirectoryConnection) build(nodes []*Directory, pager *directoryPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Directory
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Directory {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Directory {
			return nodes[i]
		}
	}
	c.Edges = make([]*DirectoryEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &DirectoryEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// DirectoryPaginateOption enables pagination customization.
type DirectoryPaginateOption func(*directoryPager) error

// WithDirectoryOrder configures pagination ordering.
func WithDirectoryOrder(order *DirectoryOrder) DirectoryPaginateOption {
	if order == nil {
		order = DefaultDirectoryOrder
	}
	o := *order
	return func(pager *directoryPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultDirectoryOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithDirectoryFilter configures pagination filter.
func WithDirectoryFilter(filter func(*DirectoryQuery) (*DirectoryQuery, error)) DirectoryPaginateOption {
	return func(pager *directoryPager) error {
		if filter == nil {
			return errors.New("DirectoryQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type directoryPager struct {
	order  *DirectoryOrder
	filter func(*DirectoryQuery) (*DirectoryQuery, error)
}

func newDirectoryPager(opts []DirectoryPaginateOption) (*directoryPager, error) {
	pager := &directoryPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultDirectoryOrder
	}
	return pager, nil
}

func (p *directoryPager) applyFilter(query *DirectoryQuery) (*DirectoryQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *directoryPager) toCursor(d *Directory) Cursor {
	return p.order.Field.toCursor(d)
}

func (p *directoryPager) applyCursors(query *DirectoryQuery, after, before *Cursor) *DirectoryQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultDirectoryOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *directoryPager) applyOrder(query *DirectoryQuery, reverse bool) *DirectoryQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultDirectoryOrder.Field {
		query = query.Order(direction.orderFunc(DefaultDirectoryOrder.Field.field))
	}
	return query
}

func (p *directoryPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultDirectoryOrder.Field {
			b.Comma().Ident(DefaultDirectoryOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Directory.
func (d *DirectoryQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...DirectoryPaginateOption,
) (*DirectoryConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newDirectoryPager(opts)
	if err != nil {
		return nil, err
	}
	if d, err = pager.applyFilter(d); err != nil {
		return nil, err
	}
	conn := &DirectoryConnection{Edges: []*DirectoryEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = d.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	d = pager.applyCursors(d, after, before)
	d = pager.applyOrder(d, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		d.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := d.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := d.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// DirectoryOrderField defines the ordering field of Directory.
type DirectoryOrderField struct {
	field    string
	toCursor func(*Directory) Cursor
}

// DirectoryOrder defines the ordering of Directory.
type DirectoryOrder struct {
	Direction OrderDirection       `json:"direction"`
	Field     *DirectoryOrderField `json:"field"`
}

// DefaultDirectoryOrder is the default ordering of Directory.
var DefaultDirectoryOrder = &DirectoryOrder{
	Direction: OrderDirectionAsc,
	Field: &DirectoryOrderField{
		field: directory.FieldID,
		toCursor: func(d *Directory) Cursor {
			return Cursor{ID: d.ID}
		},
	},
}

// ToEdge converts Directory into DirectoryEdge.
func (d *Directory) ToEdge(order *DirectoryOrder) *DirectoryEdge {
	if order == nil {
		order = DefaultDirectoryOrder
	}
	return &DirectoryEdge{
		Node:   d,
		Cursor: order.Field.toCursor(d),
	}
}

// EmailEdge is the edge representation of Email.
type EmailEdge struct {
	Node   *Email `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// EmailConnection is the connection containing edges to Email.
type EmailConnection struct {
	Edges      []*EmailEdge `json:"edges"`
	PageInfo   PageInfo     `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

func (c *EmailConnection) build(nodes []*Email, pager *emailPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Email
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Email {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Email {
			return nodes[i]
		}
	}
	c.Edges = make([]*EmailEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &EmailEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// EmailPaginateOption enables pagination customization.
type EmailPaginateOption func(*emailPager) error

// WithEmailOrder configures pagination ordering.
func WithEmailOrder(order *EmailOrder) EmailPaginateOption {
	if order == nil {
		order = DefaultEmailOrder
	}
	o := *order
	return func(pager *emailPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultEmailOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithEmailFilter configures pagination filter.
func WithEmailFilter(filter func(*EmailQuery) (*EmailQuery, error)) EmailPaginateOption {
	return func(pager *emailPager) error {
		if filter == nil {
			return errors.New("EmailQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type emailPager struct {
	order  *EmailOrder
	filter func(*EmailQuery) (*EmailQuery, error)
}

func newEmailPager(opts []EmailPaginateOption) (*emailPager, error) {
	pager := &emailPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultEmailOrder
	}
	return pager, nil
}

func (p *emailPager) applyFilter(query *EmailQuery) (*EmailQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *emailPager) toCursor(e *Email) Cursor {
	return p.order.Field.toCursor(e)
}

func (p *emailPager) applyCursors(query *EmailQuery, after, before *Cursor) *EmailQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultEmailOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *emailPager) applyOrder(query *EmailQuery, reverse bool) *EmailQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultEmailOrder.Field {
		query = query.Order(direction.orderFunc(DefaultEmailOrder.Field.field))
	}
	return query
}

func (p *emailPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultEmailOrder.Field {
			b.Comma().Ident(DefaultEmailOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Email.
func (e *EmailQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...EmailPaginateOption,
) (*EmailConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newEmailPager(opts)
	if err != nil {
		return nil, err
	}
	if e, err = pager.applyFilter(e); err != nil {
		return nil, err
	}
	conn := &EmailConnection{Edges: []*EmailEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = e.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	e = pager.applyCursors(e, after, before)
	e = pager.applyOrder(e, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		e.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := e.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := e.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// EmailOrderField defines the ordering field of Email.
type EmailOrderField struct {
	field    string
	toCursor func(*Email) Cursor
}

// EmailOrder defines the ordering of Email.
type EmailOrder struct {
	Direction OrderDirection   `json:"direction"`
	Field     *EmailOrderField `json:"field"`
}

// DefaultEmailOrder is the default ordering of Email.
var DefaultEmailOrder = &EmailOrder{
	Direction: OrderDirectionAsc,
	Field: &EmailOrderField{
		field: email.FieldID,
		toCursor: func(e *Email) Cursor {
			return Cursor{ID: e.ID}
		},
	},
}

// ToEdge converts Email into EmailEdge.
func (e *Email) ToEdge(order *EmailOrder) *EmailEdge {
	if order == nil {
		order = DefaultEmailOrder
	}
	return &EmailEdge{
		Node:   e,
		Cursor: order.Field.toCursor(e),
	}
}

// ObjectEdge is the edge representation of Object.
type ObjectEdge struct {
	Node   *Object `json:"node"`
	Cursor Cursor  `json:"cursor"`
}

// ObjectConnection is the connection containing edges to Object.
type ObjectConnection struct {
	Edges      []*ObjectEdge `json:"edges"`
	PageInfo   PageInfo      `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

func (c *ObjectConnection) build(nodes []*Object, pager *objectPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Object
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Object {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Object {
			return nodes[i]
		}
	}
	c.Edges = make([]*ObjectEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &ObjectEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// ObjectPaginateOption enables pagination customization.
type ObjectPaginateOption func(*objectPager) error

// WithObjectOrder configures pagination ordering.
func WithObjectOrder(order *ObjectOrder) ObjectPaginateOption {
	if order == nil {
		order = DefaultObjectOrder
	}
	o := *order
	return func(pager *objectPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultObjectOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithObjectFilter configures pagination filter.
func WithObjectFilter(filter func(*ObjectQuery) (*ObjectQuery, error)) ObjectPaginateOption {
	return func(pager *objectPager) error {
		if filter == nil {
			return errors.New("ObjectQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type objectPager struct {
	order  *ObjectOrder
	filter func(*ObjectQuery) (*ObjectQuery, error)
}

func newObjectPager(opts []ObjectPaginateOption) (*objectPager, error) {
	pager := &objectPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultObjectOrder
	}
	return pager, nil
}

func (p *objectPager) applyFilter(query *ObjectQuery) (*ObjectQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *objectPager) toCursor(o *Object) Cursor {
	return p.order.Field.toCursor(o)
}

func (p *objectPager) applyCursors(query *ObjectQuery, after, before *Cursor) *ObjectQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultObjectOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *objectPager) applyOrder(query *ObjectQuery, reverse bool) *ObjectQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultObjectOrder.Field {
		query = query.Order(direction.orderFunc(DefaultObjectOrder.Field.field))
	}
	return query
}

func (p *objectPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultObjectOrder.Field {
			b.Comma().Ident(DefaultObjectOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Object.
func (o *ObjectQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...ObjectPaginateOption,
) (*ObjectConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newObjectPager(opts)
	if err != nil {
		return nil, err
	}
	if o, err = pager.applyFilter(o); err != nil {
		return nil, err
	}
	conn := &ObjectConnection{Edges: []*ObjectEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = o.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	o = pager.applyCursors(o, after, before)
	o = pager.applyOrder(o, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		o.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := o.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := o.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// ObjectOrderField defines the ordering field of Object.
type ObjectOrderField struct {
	field    string
	toCursor func(*Object) Cursor
}

// ObjectOrder defines the ordering of Object.
type ObjectOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     *ObjectOrderField `json:"field"`
}

// DefaultObjectOrder is the default ordering of Object.
var DefaultObjectOrder = &ObjectOrder{
	Direction: OrderDirectionAsc,
	Field: &ObjectOrderField{
		field: object.FieldID,
		toCursor: func(o *Object) Cursor {
			return Cursor{ID: o.ID}
		},
	},
}

// ToEdge converts Object into ObjectEdge.
func (o *Object) ToEdge(order *ObjectOrder) *ObjectEdge {
	if order == nil {
		order = DefaultObjectOrder
	}
	return &ObjectEdge{
		Node:   o,
		Cursor: order.Field.toCursor(o),
	}
}

// SocialEdge is the edge representation of Social.
type SocialEdge struct {
	Node   *Social `json:"node"`
	Cursor Cursor  `json:"cursor"`
}

// SocialConnection is the connection containing edges to Social.
type SocialConnection struct {
	Edges      []*SocialEdge `json:"edges"`
	PageInfo   PageInfo      `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

func (c *SocialConnection) build(nodes []*Social, pager *socialPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Social
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Social {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Social {
			return nodes[i]
		}
	}
	c.Edges = make([]*SocialEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &SocialEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// SocialPaginateOption enables pagination customization.
type SocialPaginateOption func(*socialPager) error

// WithSocialOrder configures pagination ordering.
func WithSocialOrder(order *SocialOrder) SocialPaginateOption {
	if order == nil {
		order = DefaultSocialOrder
	}
	o := *order
	return func(pager *socialPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultSocialOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithSocialFilter configures pagination filter.
func WithSocialFilter(filter func(*SocialQuery) (*SocialQuery, error)) SocialPaginateOption {
	return func(pager *socialPager) error {
		if filter == nil {
			return errors.New("SocialQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type socialPager struct {
	order  *SocialOrder
	filter func(*SocialQuery) (*SocialQuery, error)
}

func newSocialPager(opts []SocialPaginateOption) (*socialPager, error) {
	pager := &socialPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultSocialOrder
	}
	return pager, nil
}

func (p *socialPager) applyFilter(query *SocialQuery) (*SocialQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *socialPager) toCursor(s *Social) Cursor {
	return p.order.Field.toCursor(s)
}

func (p *socialPager) applyCursors(query *SocialQuery, after, before *Cursor) *SocialQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultSocialOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *socialPager) applyOrder(query *SocialQuery, reverse bool) *SocialQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultSocialOrder.Field {
		query = query.Order(direction.orderFunc(DefaultSocialOrder.Field.field))
	}
	return query
}

func (p *socialPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultSocialOrder.Field {
			b.Comma().Ident(DefaultSocialOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Social.
func (s *SocialQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...SocialPaginateOption,
) (*SocialConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newSocialPager(opts)
	if err != nil {
		return nil, err
	}
	if s, err = pager.applyFilter(s); err != nil {
		return nil, err
	}
	conn := &SocialConnection{Edges: []*SocialEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = s.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	s = pager.applyCursors(s, after, before)
	s = pager.applyOrder(s, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		s.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := s.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := s.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

var (
	// SocialOrderFieldName orders Social by name.
	SocialOrderFieldName = &SocialOrderField{
		field: social.FieldName,
		toCursor: func(s *Social) Cursor {
			return Cursor{
				ID:    s.ID,
				Value: s.Name,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f SocialOrderField) String() string {
	var str string
	switch f.field {
	case social.FieldName:
		str = "NAME"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f SocialOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *SocialOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("SocialOrderField %T must be a string", v)
	}
	switch str {
	case "NAME":
		*f = *SocialOrderFieldName
	default:
		return fmt.Errorf("%s is not a valid SocialOrderField", str)
	}
	return nil
}

// SocialOrderField defines the ordering field of Social.
type SocialOrderField struct {
	field    string
	toCursor func(*Social) Cursor
}

// SocialOrder defines the ordering of Social.
type SocialOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     *SocialOrderField `json:"field"`
}

// DefaultSocialOrder is the default ordering of Social.
var DefaultSocialOrder = &SocialOrder{
	Direction: OrderDirectionAsc,
	Field: &SocialOrderField{
		field: social.FieldID,
		toCursor: func(s *Social) Cursor {
			return Cursor{ID: s.ID}
		},
	},
}

// ToEdge converts Social into SocialEdge.
func (s *Social) ToEdge(order *SocialOrder) *SocialEdge {
	if order == nil {
		order = DefaultSocialOrder
	}
	return &SocialEdge{
		Node:   s,
		Cursor: order.Field.toCursor(s),
	}
}

// UserEdge is the edge representation of User.
type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// UserConnection is the connection containing edges to User.
type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *UserConnection) build(nodes []*User, pager *userPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *User
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *User {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *User {
			return nodes[i]
		}
	}
	c.Edges = make([]*UserEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &UserEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// UserPaginateOption enables pagination customization.
type UserPaginateOption func(*userPager) error

// WithUserOrder configures pagination ordering.
func WithUserOrder(order *UserOrder) UserPaginateOption {
	if order == nil {
		order = DefaultUserOrder
	}
	o := *order
	return func(pager *userPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultUserOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithUserFilter configures pagination filter.
func WithUserFilter(filter func(*UserQuery) (*UserQuery, error)) UserPaginateOption {
	return func(pager *userPager) error {
		if filter == nil {
			return errors.New("UserQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type userPager struct {
	order  *UserOrder
	filter func(*UserQuery) (*UserQuery, error)
}

func newUserPager(opts []UserPaginateOption) (*userPager, error) {
	pager := &userPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultUserOrder
	}
	return pager, nil
}

func (p *userPager) applyFilter(query *UserQuery) (*UserQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *userPager) toCursor(u *User) Cursor {
	return p.order.Field.toCursor(u)
}

func (p *userPager) applyCursors(query *UserQuery, after, before *Cursor) *UserQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultUserOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *userPager) applyOrder(query *UserQuery, reverse bool) *UserQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultUserOrder.Field {
		query = query.Order(direction.orderFunc(DefaultUserOrder.Field.field))
	}
	return query
}

func (p *userPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultUserOrder.Field {
			b.Comma().Ident(DefaultUserOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to User.
func (u *UserQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...UserPaginateOption,
) (*UserConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newUserPager(opts)
	if err != nil {
		return nil, err
	}
	if u, err = pager.applyFilter(u); err != nil {
		return nil, err
	}
	conn := &UserConnection{Edges: []*UserEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = u.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	u = pager.applyCursors(u, after, before)
	u = pager.applyOrder(u, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		u.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := u.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := u.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

var (
	// UserOrderFieldName orders User by name.
	UserOrderFieldName = &UserOrderField{
		field: user.FieldName,
		toCursor: func(u *User) Cursor {
			return Cursor{
				ID:    u.ID,
				Value: u.Name,
			}
		},
	}
	// UserOrderFieldPassword orders User by password.
	UserOrderFieldPassword = &UserOrderField{
		field: user.FieldPassword,
		toCursor: func(u *User) Cursor {
			return Cursor{
				ID:    u.ID,
				Value: u.Password,
			}
		},
	}
	// UserOrderFieldPhone orders User by phone.
	UserOrderFieldPhone = &UserOrderField{
		field: user.FieldPhone,
		toCursor: func(u *User) Cursor {
			return Cursor{
				ID:    u.ID,
				Value: u.Phone,
			}
		},
	}
)

// String implement fmt.Stringer interface.
func (f UserOrderField) String() string {
	var str string
	switch f.field {
	case user.FieldName:
		str = "NAME"
	case user.FieldPassword:
		str = "PASSWORD"
	case user.FieldPhone:
		str = "PHONE"
	}
	return str
}

// MarshalGQL implements graphql.Marshaler interface.
func (f UserOrderField) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(f.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (f *UserOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("UserOrderField %T must be a string", v)
	}
	switch str {
	case "NAME":
		*f = *UserOrderFieldName
	case "PASSWORD":
		*f = *UserOrderFieldPassword
	case "PHONE":
		*f = *UserOrderFieldPhone
	default:
		return fmt.Errorf("%s is not a valid UserOrderField", str)
	}
	return nil
}

// UserOrderField defines the ordering field of User.
type UserOrderField struct {
	field    string
	toCursor func(*User) Cursor
}

// UserOrder defines the ordering of User.
type UserOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *UserOrderField `json:"field"`
}

// DefaultUserOrder is the default ordering of User.
var DefaultUserOrder = &UserOrder{
	Direction: OrderDirectionAsc,
	Field: &UserOrderField{
		field: user.FieldID,
		toCursor: func(u *User) Cursor {
			return Cursor{ID: u.ID}
		},
	},
}

// ToEdge converts User into UserEdge.
func (u *User) ToEdge(order *UserOrder) *UserEdge {
	if order == nil {
		order = DefaultUserOrder
	}
	return &UserEdge{
		Node:   u,
		Cursor: order.Field.toCursor(u),
	}
}

// WechatEdge is the edge representation of Wechat.
type WechatEdge struct {
	Node   *Wechat `json:"node"`
	Cursor Cursor  `json:"cursor"`
}

// WechatConnection is the connection containing edges to Wechat.
type WechatConnection struct {
	Edges      []*WechatEdge `json:"edges"`
	PageInfo   PageInfo      `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

func (c *WechatConnection) build(nodes []*Wechat, pager *wechatPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Wechat
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Wechat {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Wechat {
			return nodes[i]
		}
	}
	c.Edges = make([]*WechatEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &WechatEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// WechatPaginateOption enables pagination customization.
type WechatPaginateOption func(*wechatPager) error

// WithWechatOrder configures pagination ordering.
func WithWechatOrder(order *WechatOrder) WechatPaginateOption {
	if order == nil {
		order = DefaultWechatOrder
	}
	o := *order
	return func(pager *wechatPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultWechatOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithWechatFilter configures pagination filter.
func WithWechatFilter(filter func(*WechatQuery) (*WechatQuery, error)) WechatPaginateOption {
	return func(pager *wechatPager) error {
		if filter == nil {
			return errors.New("WechatQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type wechatPager struct {
	order  *WechatOrder
	filter func(*WechatQuery) (*WechatQuery, error)
}

func newWechatPager(opts []WechatPaginateOption) (*wechatPager, error) {
	pager := &wechatPager{}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultWechatOrder
	}
	return pager, nil
}

func (p *wechatPager) applyFilter(query *WechatQuery) (*WechatQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *wechatPager) toCursor(w *Wechat) Cursor {
	return p.order.Field.toCursor(w)
}

func (p *wechatPager) applyCursors(query *WechatQuery, after, before *Cursor) *WechatQuery {
	for _, predicate := range cursorsToPredicates(
		p.order.Direction, after, before,
		p.order.Field.field, DefaultWechatOrder.Field.field,
	) {
		query = query.Where(predicate)
	}
	return query
}

func (p *wechatPager) applyOrder(query *WechatQuery, reverse bool) *WechatQuery {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	query = query.Order(direction.orderFunc(p.order.Field.field))
	if p.order.Field != DefaultWechatOrder.Field {
		query = query.Order(direction.orderFunc(DefaultWechatOrder.Field.field))
	}
	return query
}

func (p *wechatPager) orderExpr(reverse bool) sql.Querier {
	direction := p.order.Direction
	if reverse {
		direction = direction.reverse()
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.field).Pad().WriteString(string(direction))
		if p.order.Field != DefaultWechatOrder.Field {
			b.Comma().Ident(DefaultWechatOrder.Field.field).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Wechat.
func (w *WechatQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...WechatPaginateOption,
) (*WechatConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newWechatPager(opts)
	if err != nil {
		return nil, err
	}
	if w, err = pager.applyFilter(w); err != nil {
		return nil, err
	}
	conn := &WechatConnection{Edges: []*WechatEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = w.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}

	w = pager.applyCursors(w, after, before)
	w = pager.applyOrder(w, last != nil)
	if limit := paginateLimit(first, last); limit != 0 {
		w.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := w.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}

	nodes, err := w.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// WechatOrderField defines the ordering field of Wechat.
type WechatOrderField struct {
	field    string
	toCursor func(*Wechat) Cursor
}

// WechatOrder defines the ordering of Wechat.
type WechatOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     *WechatOrderField `json:"field"`
}

// DefaultWechatOrder is the default ordering of Wechat.
var DefaultWechatOrder = &WechatOrder{
	Direction: OrderDirectionAsc,
	Field: &WechatOrderField{
		field: wechat.FieldID,
		toCursor: func(w *Wechat) Cursor {
			return Cursor{ID: w.ID}
		},
	},
}

// ToEdge converts Wechat into WechatEdge.
func (w *Wechat) ToEdge(order *WechatOrder) *WechatEdge {
	if order == nil {
		order = DefaultWechatOrder
	}
	return &WechatEdge{
		Node:   w,
		Cursor: order.Field.toCursor(w),
	}
}
