// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"drive/ent/email"
	"drive/ent/predicate"
	"drive/ent/social"
	"drive/ent/wechat"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SocialQuery is the builder for querying Social entities.
type SocialQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.Social
	withEmail  *EmailQuery
	withWechat *WechatQuery
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*Social) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SocialQuery builder.
func (sq *SocialQuery) Where(ps ...predicate.Social) *SocialQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit adds a limit step to the query.
func (sq *SocialQuery) Limit(limit int) *SocialQuery {
	sq.limit = &limit
	return sq
}

// Offset adds an offset step to the query.
func (sq *SocialQuery) Offset(offset int) *SocialQuery {
	sq.offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SocialQuery) Unique(unique bool) *SocialQuery {
	sq.unique = &unique
	return sq
}

// Order adds an order step to the query.
func (sq *SocialQuery) Order(o ...OrderFunc) *SocialQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryEmail chains the current query on the "email" edge.
func (sq *SocialQuery) QueryEmail() *EmailQuery {
	query := &EmailQuery{config: sq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(social.Table, social.FieldID, selector),
			sqlgraph.To(email.Table, email.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, social.EmailTable, social.EmailColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWechat chains the current query on the "wechat" edge.
func (sq *SocialQuery) QueryWechat() *WechatQuery {
	query := &WechatQuery{config: sq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(social.Table, social.FieldID, selector),
			sqlgraph.To(wechat.Table, wechat.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, social.WechatTable, social.WechatColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Social entity from the query.
// Returns a *NotFoundError when no Social was found.
func (sq *SocialQuery) First(ctx context.Context) (*Social, error) {
	nodes, err := sq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{social.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SocialQuery) FirstX(ctx context.Context) *Social {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Social ID from the query.
// Returns a *NotFoundError when no Social ID was found.
func (sq *SocialQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = sq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{social.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SocialQuery) FirstIDX(ctx context.Context) int64 {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Social entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Social entity is found.
// Returns a *NotFoundError when no Social entities are found.
func (sq *SocialQuery) Only(ctx context.Context) (*Social, error) {
	nodes, err := sq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{social.Label}
	default:
		return nil, &NotSingularError{social.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SocialQuery) OnlyX(ctx context.Context) *Social {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Social ID in the query.
// Returns a *NotSingularError when more than one Social ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SocialQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = sq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{social.Label}
	default:
		err = &NotSingularError{social.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SocialQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Socials.
func (sq *SocialQuery) All(ctx context.Context) ([]*Social, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sq *SocialQuery) AllX(ctx context.Context) []*Social {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Social IDs.
func (sq *SocialQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := sq.Select(social.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SocialQuery) IDsX(ctx context.Context) []int64 {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SocialQuery) Count(ctx context.Context) (int, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SocialQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SocialQuery) Exist(ctx context.Context) (bool, error) {
	if err := sq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SocialQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SocialQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SocialQuery) Clone() *SocialQuery {
	if sq == nil {
		return nil
	}
	return &SocialQuery{
		config:     sq.config,
		limit:      sq.limit,
		offset:     sq.offset,
		order:      append([]OrderFunc{}, sq.order...),
		predicates: append([]predicate.Social{}, sq.predicates...),
		withEmail:  sq.withEmail.Clone(),
		withWechat: sq.withWechat.Clone(),
		// clone intermediate query.
		sql:    sq.sql.Clone(),
		path:   sq.path,
		unique: sq.unique,
	}
}

// WithEmail tells the query-builder to eager-load the nodes that are connected to
// the "email" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SocialQuery) WithEmail(opts ...func(*EmailQuery)) *SocialQuery {
	query := &EmailQuery{config: sq.config}
	for _, opt := range opts {
		opt(query)
	}
	sq.withEmail = query
	return sq
}

// WithWechat tells the query-builder to eager-load the nodes that are connected to
// the "wechat" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SocialQuery) WithWechat(opts ...func(*WechatQuery)) *SocialQuery {
	query := &WechatQuery{config: sq.config}
	for _, opt := range opts {
		opt(query)
	}
	sq.withWechat = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy int64 `json:"created_by"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Social.Query().
//		GroupBy(social.FieldCreatedBy).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SocialQuery) GroupBy(field string, fields ...string) *SocialGroupBy {
	grbuild := &SocialGroupBy{config: sq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sq.sqlQuery(ctx), nil
	}
	grbuild.label = social.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy int64 `json:"created_by"`
//	}
//
//	client.Social.Query().
//		Select(social.FieldCreatedBy).
//		Scan(ctx, &v)
func (sq *SocialQuery) Select(fields ...string) *SocialSelect {
	sq.fields = append(sq.fields, fields...)
	selbuild := &SocialSelect{SocialQuery: sq}
	selbuild.label = social.Label
	selbuild.flds, selbuild.scan = &sq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a SocialSelect configured with the given aggregations.
func (sq *SocialQuery) Aggregate(fns ...AggregateFunc) *SocialSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SocialQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sq.fields {
		if !social.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SocialQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Social, error) {
	var (
		nodes       = []*Social{}
		_spec       = sq.querySpec()
		loadedTypes = [2]bool{
			sq.withEmail != nil,
			sq.withWechat != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Social).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Social{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withEmail; query != nil {
		if err := sq.loadEmail(ctx, query, nodes, nil,
			func(n *Social, e *Email) { n.Edges.Email = e }); err != nil {
			return nil, err
		}
	}
	if query := sq.withWechat; query != nil {
		if err := sq.loadWechat(ctx, query, nodes, nil,
			func(n *Social, e *Wechat) { n.Edges.Wechat = e }); err != nil {
			return nil, err
		}
	}
	for i := range sq.loadTotal {
		if err := sq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SocialQuery) loadEmail(ctx context.Context, query *EmailQuery, nodes []*Social, init func(*Social), assign func(*Social, *Email)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Social)
	for i := range nodes {
		fk := nodes[i].RelationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(email.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "relation_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (sq *SocialQuery) loadWechat(ctx context.Context, query *WechatQuery, nodes []*Social, init func(*Social), assign func(*Social, *Wechat)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Social)
	for i := range nodes {
		fk := nodes[i].RelationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(wechat.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "relation_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sq *SocialQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	if len(sq.modifiers) > 0 {
		_spec.Modifiers = sq.modifiers
	}
	_spec.Node.Columns = sq.fields
	if len(sq.fields) > 0 {
		_spec.Unique = sq.unique != nil && *sq.unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SocialQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (sq *SocialQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   social.Table,
			Columns: social.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: social.FieldID,
			},
		},
		From:   sq.sql,
		Unique: true,
	}
	if unique := sq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, social.FieldID)
		for i := range fields {
			if fields[i] != social.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SocialQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(social.Table)
	columns := sq.fields
	if len(columns) == 0 {
		columns = social.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.unique != nil && *sq.unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SocialGroupBy is the group-by builder for Social entities.
type SocialGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SocialGroupBy) Aggregate(fns ...AggregateFunc) *SocialGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the group-by query and scans the result into the given value.
func (sgb *SocialGroupBy) Scan(ctx context.Context, v any) error {
	query, err := sgb.path(ctx)
	if err != nil {
		return err
	}
	sgb.sql = query
	return sgb.sqlScan(ctx, v)
}

func (sgb *SocialGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range sgb.fields {
		if !social.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sgb *SocialGroupBy) sqlQuery() *sql.Selector {
	selector := sgb.sql.Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sgb.fields)+len(sgb.fns))
		for _, f := range sgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sgb.fields...)...)
}

// SocialSelect is the builder for selecting fields of Social entities.
type SocialSelect struct {
	*SocialQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SocialSelect) Aggregate(fns ...AggregateFunc) *SocialSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SocialSelect) Scan(ctx context.Context, v any) error {
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	ss.sql = ss.SocialQuery.sqlQuery(ctx)
	return ss.sqlScan(ctx, v)
}

func (ss *SocialSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(ss.sql))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ss.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ss.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ss.sql.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
