// Code generated by ent, DO NOT EDIT.

package ent

import (
	"drive/ent/wechat"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// Wechat is the model entity for the Wechat schema.
type Wechat struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WechatQuery when eager-loading is set.
	Edges WechatEdges `json:"edges"`
}

// WechatEdges holds the relations/edges for other nodes in the graph.
type WechatEdges struct {
	// Socials holds the value of the socials edge.
	Socials []*Social `json:"socials,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedSocials map[string][]*Social
}

// SocialsOrErr returns the Socials value or an error if the edge
// was not loaded in eager-loading.
func (e WechatEdges) SocialsOrErr() ([]*Social, error) {
	if e.loadedTypes[0] {
		return e.Socials, nil
	}
	return nil, &NotLoadedError{edge: "socials"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Wechat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wechat.FieldID, wechat.FieldCreatedBy, wechat.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case wechat.FieldName:
			values[i] = new(sql.NullString)
		case wechat.FieldCreatedAt, wechat.FieldUpdatedAt, wechat.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Wechat", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Wechat fields.
func (w *Wechat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wechat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			w.ID = int64(value.Int64)
		case wechat.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				w.CreatedBy = value.Int64
			}
		case wechat.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				w.UpdatedBy = value.Int64
			}
		case wechat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				w.CreatedAt = value.Time
			}
		case wechat.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				w.UpdatedAt = value.Time
			}
		case wechat.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				w.DeletedAt = value.Time
			}
		case wechat.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				w.Name = value.String
			}
		}
	}
	return nil
}

// QuerySocials queries the "socials" edge of the Wechat entity.
func (w *Wechat) QuerySocials() *SocialQuery {
	return (&WechatClient{config: w.config}).QuerySocials(w)
}

// Update returns a builder for updating this Wechat.
// Note that you need to call Wechat.Unwrap() before calling this method if this Wechat
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Wechat) Update() *WechatUpdateOne {
	return (&WechatClient{config: w.config}).UpdateOne(w)
}

// Unwrap unwraps the Wechat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (w *Wechat) Unwrap() *Wechat {
	_tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Wechat is not a transactional entity")
	}
	w.config.driver = _tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Wechat) String() string {
	var builder strings.Builder
	builder.WriteString("Wechat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", w.ID))
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", w.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", w.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(w.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(w.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(w.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(w.Name)
	builder.WriteByte(')')
	return builder.String()
}

// NamedSocials returns the Socials named value or an error if the edge was not
// loaded in eager-loading with this name.
func (w *Wechat) NamedSocials(name string) ([]*Social, error) {
	if w.Edges.namedSocials == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := w.Edges.namedSocials[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (w *Wechat) appendNamedSocials(name string, edges ...*Social) {
	if w.Edges.namedSocials == nil {
		w.Edges.namedSocials = make(map[string][]*Social)
	}
	if len(edges) == 0 {
		w.Edges.namedSocials[name] = []*Social{}
	} else {
		w.Edges.namedSocials[name] = append(w.Edges.namedSocials[name], edges...)
	}
}

// Wechats is a parsable slice of Wechat.
type Wechats []*Wechat

func (w Wechats) config(cfg config) {
	for _i := range w {
		w[_i].config = cfg
	}
}
